### PR TITLE
Added trial hierarchy of building system

### PR DESCRIPTION
**Pull request by kolobabka**

### CODE REVIEW

**Comment by kolobabka** [comment]
@Exactlywb, @pavel-collab,
Please, review it, try on your machines and ask your questions

**Comment by Exactlywb** [comment]
Looks well to me but some issues is still relevant:

1) I've not found .clang-format file so it looks like `make format` doesn't work just now.
2) It doesn't seem to me that uncommenting lines with run-clang is the best way.  Maybe it'd be better to submit flag in cmake running like
```
$ cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_RUN_CLANG=1
```
3) Update README.md pls

**Comment by pavel-collab** [comment]
1. Remove commented parts of code.
2. Need to write requirements for the system (if it need of course) like: tools for build and installing, compiler version etc.
3. In my opinion, it need to add comments for the basic parts of code. For example if we have static char S array, I think it need to write a comment, that provide to understand what is it and where do we use it. It need to make code navigation faster and more clear understanding.
4. Make a small build instruction (especially for me, as I don't check the project as often as you).

Thank you for attention to details!

**Comment by kolobabka** [comment]
Thakns for your comments. I will consider all these notes this evening

**Comment by kolobabka** [comment]
I've updated README and add .clang-format file (you can configure it in another way -- make a new PR :) ).
LGTM for me

**Comment by Exactlywb** [comment]
Confirmed.

**Pull request merged**
